### ISSUE TITLE
CRAM files

### ISSUE THREAD

**Issue by rebekabato** [edawson/check-sex#4]
Hi, thanks for this helpful script! 
It does not seem to work with CRAM files, am I right? Any suggestion for modifications so that the script can take CRAM files too?

Many thanks!
Reb

**Comment by edawson** [comment]
Interesting question - the tool uses [samtools idxstats](http://www.htslib.org/doc/samtools-idxstats.html) to count mapped reads, While it should work with CRAM files, the docs indicate it will be slow as it must iterate through the entire CRAM / SAM.
